name: 'Slack Alert'
description: 'Greet someone and record the time'
inputs:
  slack_url: 
    description: 'Slack URL'
    required: true
  message:
    description: 'Message to be sent'
    required: true
  actor: 
    description: 'Message to be sent'
    required: true
  environment:
    description: 'Environment Release'
    required: true
  release:
    description: 'Release & Tag'
    required: true
  status:  
    description: 'Status'
    required: true
outputs:
  time: 
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'